---
title: "Untitled"
author: "John Wright"
date: "Wednesday, February 11, 2015"
output: html_document
---

```{r}
library(party)
library(randomForest)
library(lubridate)
library(lattice)
library(gbm)
library(ProgGUIinR)
library(neuralnet)
library(e1071)

setwd("C:\\Users\\jwright\\Desktop\\p5")

train <- read.csv("train.csv", header = T)
test <- read.csv("test.csv", header = T)

```


# prepare data
```{r}

# fix data types
cleaner <- function(x) {
      x$datetime <- as.POSIXct(x$datetime)
      x[, 2:5] <- lapply(x[, 2:5], factor)
      x[, c(6:7, 9)] <- lapply(x[, c(6:7, 9)], as.numeric)
#       x[, 8] <- lapply(x[, 8], function(x) as.integer(as.character(x)))
      x
}

train <- cleaner(train); test <- cleaner(test)

# generate new features
dataPrep <- function(x) {
      x$year <- factor(year(x$datetime))
      x$month <- factor(months(x$datetime))
      x$week <- factor(with(x, week.of.month(year(datetime),
                                             month(datetime),
                                             day(datetime))))
      x$day <- factor(weekdays(x$datetime))
      x$daynum <- factor(day(x$datetime))
      x$hour <- factor(as.integer(format(x$datetime, format = "%H")))
      x$is_sun <- factor(ifelse(x$day == "Sunday", 1, 0))
      x$is_sat <- factor(ifelse(x$day == "Saturday", 1, 0))
      
      ## Holiday Adjustments ######################################################
      # xmas / NYE
      x$holiday[x$month == "December" & x$daynum %in% c(23, 24, 25, 26, 31)] <- 1
      
      # thanksgiving
      x$holiday[x$month == "November" & x$week == 3 & (x$day == "Wednesday" |
                                                      x$day == "Thursday" | 
                                                      x$day == "Friday")] <- 1
      
      # halloween
#       x$holiday[x$month == "October" & x$daynum == 31] <- 1
      
      # labor day
      x$holiday[x$month == "September" & x$week == 1 & x$day == "Monday"] <- 1
      
      # independence day
      x$holiday[x$month == "July" & x$daynum == 4] <- 1
      
      # memorial day
      x$holiday[x$month == "May" & x$day == "Monday" & x$week == 4] <- 1
      
      # pres day
      x$holiday[x$month == "February" & x$weeknum == 3 & x$day == "Monday"] <- 1
      
      # MLK day
      x$holiday[x$month == "January" & x$week == 3 & x$day == "Monday"] <- 1
      
      # new years day
      x$holiday[x$month == "January" & x$daynum == 1] <- 1
      
      # superbowl
      x$holiday[x$month == "February" & x$daynum == 6 & x$year == 2011] <- 1
      x$holiday[x$month == "February" & x$daynum == 5 & x$year == 2012] <- 1
      
      # Washington DC Marathon
      x$holiday[x$month == "March" & x$daynum == 17 & x$year == 2012] <- 1
      x$holiday[x$month == "March" & x$daynum == 26 & x$year == 2011] <- 1
      #############################################################################
      
      for (d in unique(x$day)) {
            x[, d] <- factor(ifelse(x$day == d, 1, 0))
      }
#       for (m in unique(x$month)) {
#             x[, m] <- factor(ifelse(x$month == m, 1, 0))
#       }

      x$temp_b <- cut(x$temp, 
                      breaks = c(-1, 10, 15, 24, 31, 100),
                      labels = c("cold", "chilly", "comfortable", "warm", "hot"))
      x$atemp_b <- cut(x$atemp, 
                       breaks = c(-1, 10, 15, 24, 31, 100),
                       labels = c("cold", "chilly", "comfortable", "warm", "hot"))
      x$windy <- factor(ifelse(x$windspeed > 35, 1, 0))
      x$timerange <- cut(as.numeric(x$hour),
                         breaks = c(0, 7, 12, 17, 21, 24),
                         labels = c("early", "morning", "afternoon", "evening", "night"))
      
      x$humidity_b <- cut(x$humidity,
                          breaks = c(-1, 25, 60, 101),
                          labels = c("low", "comfortable", "sticky"))



      x$busy <- "verylow"
      x$busy[x$hour %in% c(0, 6, 22, 23)] <- "low"
      x$busy[x$hour %in% c(9, 10, 20, 21)] <- "moderate"
      x$busy[x$hour %in% c(7, 11, 12, 13, 14, 15, 16, 19)] <- "high"
      x$busy[x$hour %in% c(8, 17, 18)] <- "veryhigh"
      x$busy <- factor(x$busy)
      
      # total stations
      x$stations <- 0
      x$stations[x$datetime > "2011-04-11"] <- 25
      x$stations[x$datetime > "2011-07-27"] <- 57
      x$stations[x$datetime > "2012-03-16"] <- 59
      x$stations[x$datetime > "2012-10-30"] <- 117
      x$stations <- factor(x$stations)
      
#       hardly any values where weather == 4 (1 in train and 2 in test)
      x$weather[x$weather == 4] <- 3
      
      x
      
}

train[, c("registered", "casual", "count")] <- lapply(train[, c("registered", "casual", "count")], log1p)
train <- dataPrep(train); test <- dataPrep(test)

# http://blog.dato.com/using-gradient-boosted-trees-to-predict-bike-sharing-demand
# http://beyondvalence.blogspot.com/2014/06/predicting-capital-bikeshare-demand-in.html

# exploratory graphs
xyplot(expm1(casual) ~ 1:nrow(train) | hour, data = train, group = month)

```

# model
```{r}
set.seed(123)

# model formula
trainVars <- "~ year + season + month + 
              holiday + workingday + weather + 
              hour + day +
              temp + atemp + 
              humidity + 
              windspeed"

#  + windy
#  + day
#               timerange + busy +
#               is_sat + is_sun + 
# + temp_b + atemp_b 


# fit the models

# randomforest
rf.fit.reg <- randomForest(as.formula(paste("registered", trainVars)), train,
                           ntree = 1000, mtry = 6)
rf.fit.cas <- randomForest(as.formula(paste("casual", trainVars)), train,
                           ntree = 1000, mtry = 6)

rf.pred.reg <- expm1(predict(rf.fit.reg, test))
rf.pred.cas <- expm1(predict(rf.fit.cas, test))

both <- data.frame(rf.pred.reg, rf.pred.cas)

preds <- rowSums(both, na.rm = T)

# svm
svm.fit.reg <- svm(as.formula(paste("registered", trainVars)), train)
svm.fit.cas <- svm(as.formula(paste("casual", trainVars)), train)

svm.pred.reg <- expm1(predict(svm.fit.reg, test))
svm.pred.cas <- expm1(predict(svm.fit.cas, test))
preds.svm <- rowSums(data.frame(svm.pred.reg, svm.pred.cas), na.rm = T)

# submission output file for svm
submit_svm <- data.frame(datetime = test$datetime, count = as.integer(preds.svm))

# submission output file for rf
submit_rf <- data.frame(datetime = test$datetime, count = as.integer(preds))

# submission for ensemble
submit_ens <- data.frame(datetime = test$datetime,
                         count = rowMeans(data.frame(preds, preds.svm), na.rm = T))

# write.csv(submit_ens, "bag_20150305.csv", row.names = F)

qplot(train$datetime, 
      expm1(train$count), 
      xlim = c(min(train$datetime), max(test$datetime)),
      color = "skyblue") + 
      geom_point(data = submit_rf, aes(datetime, count, color = "salmon")) + 
      theme(legend.position = 0)

highcount <- train[train$count > quantile(train$count, probs = .75), ]
# xyplot(expm1(casual) ~ 1:nrow(highcount) | day, data = highcount, group = holiday)

# check which model performs better on different time frames
rf.pred.train.reg <- expm1(predict(rf.fit.reg, train))
rf.pred.train.cas <- expm1(predict(rf.fit.cas, train))
svm.pred.train.reg <- expm1(predict(svm.fit.reg, train))
svm.pred.train.cas <- expm1(predict(svm.fit.cas, train))

compare <- data.frame(
      datetime = train$datetime,
      hour = train$hour,
      month = train$month,
      actual.reg = expm1(train$registered),
      actual.cas = expm1(train$casual),
      actual.count = expm1(train$count),
      rf.reg = as.integer(rf.pred.train.reg),
      rf.cas = as.integer(rf.pred.train.cas),
      rf.count = as.integer(rowSums(data.frame(rf.pred.train.reg, rf.pred.train.cas))),
      svm.reg = as.integer(svm.pred.train.reg),
      svm.cas = as.integer(svm.pred.train.cas),
      svm.count = as.integer(rowSums(data.frame(svm.pred.train.reg, svm.pred.train.cas)))
      )
compare$rf.reg.error <- as.integer(abs(compare$rf.reg - compare$actual.reg))
compare$rf.cas.error <- as.integer(abs(compare$rf.cas - compare$actual.cas))
compare$rf.error <- as.integer(abs(compare$rf.count - compare$actual.count))
compare$svm.reg.error <- as.integer(abs(compare$svm.reg - compare$actual.reg))
compare$svm.cas.error <- as.integer(abs(compare$svm.cas - compare$actual.cas))
compare$svm.error <- as.integer(abs(compare$svm.count - compare$actual.count))

```

```{r}

## neural net
# http://www.evanvanness.com/post/100217670076/neuralnet-r-package-neural-network-to-predict

# prep train data
tmat.reg <- model.matrix(as.formula(paste("registered", trainVars)), train)
tmat.cas <- model.matrix(as.formula(paste("casual", trainVars)), train)
tmat.reg <- as.data.frame(tmat.reg)
tmat.cas <- as.data.frame(tmat.cas)
tmat.reg <- cbind(tmat.reg, train$registered); names(tmat.reg)[70] <- "registered"
tmat.cas <- cbind(tmat.cas, train$casual); names(tmat.cas)[70] <- "casual"

# prep test data
test.nn <- as.data.frame(model.matrix(as.formula(trainVars), data = test))
test.nn <- test.nn[, 2:ncol(test.nn)]

# training data cleanup
names(tmat.reg)[1] <- "year2011"; names(tmat.cas)[1] <- "year2011"
nnVars <- paste(names(tmat.reg)[1:69], collapse = "+")

f.reg <- as.formula(paste("registered ~", nnVars))
f.cas <- as.formula(paste("casual ~", nnVars))

# nn model for registered
nn.fit.reg <- neuralnet(f.reg, tmat.reg, 
                        hidden = c(7, 8, 9, 8, 7), 
                        threshold = .04,
                        stepmax = 1e+06,
                        learningrate = .001,
                        algorithm = "rprop+",
                        lifesign = "full",
                        likelihood = T)

# nn model for casual
nn.fit.cas <- neuralnet(f.cas, tmat.cas, 
                        hidden = c(7, 8, 9, 8, 7), 
                        threshold = .04,
                        stepmax = 1e+06,
                        learningrate = .001,
                        algorithm = "rprop+",
                        lifesign = "full",
                        likelihood = T)

# predictions
nn.pred.reg <- expm1(compute(nn.fit.reg, test.nn)$net.rsult)
nn.pred.cas <- expm1(compute(nn.fit.cas, test.nn)$net.rsult)

nn.preds <- nn.pred.reg + nn.pred.cas
nn.preds[nn.preds < 0] <- 1

# submission output file for nn
submit_nn <- data.frame(datetime = test$datetime, count = as.integer(nn.preds))
write.csv(submit_nn, "nn_20150226.csv", row.names = F)



# FIND A WAY TO ADJUST FOR XMAS/NYE AND THXGIVING - THESE ARE NOT IN TRAIN SET
### maybe: if month == november & day = thursday & week = 3 then holiday = 1?
# the company was expanding throughout the time period. find a way to adjust
# for total number of stations
# http://www.capitalbikeshare.com/news/2012/10
# next add neural network

```

# old stuff
```{r}

# old formula:
# trainVars <- "~ year + season + holiday + workingday + weather + 
#               hour + atemp_b + windy + 
#               is_sat + is_sun + month + day +
#               timerange + busy + temp_b"


# ctree
# ctree.fit.reg <- ctree(as.formula(paste("registered", trainVars)), train)
# ctree.fit.cas <- ctree(as.formula(paste("casual", trainVars)), train)
# ctree.pred.reg <- expm1(predict(ctree.fit.reg, test))
# ctree.pred.cas <- expm1(predict(ctree.fit.cas, test))

# # gbm
# gbm.fit.reg <- gbm(as.formula(paste("registered", trainVars)), data = train)
# gbm.fit.cas <- gbm(as.formula(paste("casual", trainVars)), data = train)
# gbm.pred.reg <- expm1(predict(gbm.fit.reg, newdata = test,
#                               n.trees = gbm.fit.reg$n.trees))
# gbm.pred.cas <- expm1(predict(gbm.fit.cas, newdata = test,
#                               n.trees = gbm.fit.cas$n.trees))

# average the models together
# preds <- rowMeans(data.frame(ctree = (ctree.pred.reg + ctree.pred.cas),
#                              rf = (rf.pred.reg + rf.pred.cas)
#                              ), na.rm = T)

# old nn
# 
# nn.fit.reg <- nnet(as.formula(paste("registered", trainVars)), train, size = 10)
# 
# nn.pred.reg <- expm1(predict(nn.fit.reg, test))


# lm.fit.reg <- lm(as.formula(paste("registered", trainVars)), train)
# lm.fit.cas <- lm(as.formula(paste("casual", trainVars)), train)
# lm.pred.reg <- expm1(predict(lm.fit.reg, test))
# lm.pred.cas <- expm1(predict(lm.fit.cas, test))
# bothlm <- data.frame(lm.pred.reg, lm.pred.cas)
# bothlm <- sapply(bothlm, function(x) ifelse(x < 0, 0, x))
# preds.lm <- as.integer(rowSums(bothlm, na.rm = T))
# submit_lm <- data.frame(datetime = test$datetime, count = preds.lm)



```
